name: y_todo
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization      
  intl: ^0.17.0

  # State management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0

  # CodeGen
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  freezed: ^2.1.0+1

  # Firebase
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13
  firebase_analytics: ^9.3.0

  # Logger
  logging: ^1.0.2

  # Id gen
  uuid: ^3.0.6
  device_info_plus: ^4.0.1

  # Local Persistance
  sqflite: ^2.0.3
  path: ^1.8.1
  path_provider: ^2.0.11

  # preview
  device_preview: ^1.1.0


  

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"

flutter:
  generate: true 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
